version: "3"


x-env: &env
  restart: unless-stopped
  networks:
    - default
  volumes:
    - ./data/nas:/data

services:
  radarr:
    <<: *env
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - ./data/radarr:/config
      - ./data/nas:/data
    ports:
      - 7878:7878
  sonarr:
    <<: *env
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ./data/sonarr:/config
    ports:
      - 8989:8989

  bazarr:
    <<: *env
    image: cr.hotio.dev/hotio/bazarr
    container_name: bazarr
    volumes:
      - ./data/bazarr:/config
      - ./data/nas:/data
    ports:
      - 6767:6767

  overseerr:
    <<: *env
    image: sctx/overseerr:latest
    container_name: overseerr
    depends_on:
      - plex
    environment:
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ./data/overseerr:/app/config

  prowlarr:
    container_name: prowlarr
    <<: *env
    image: cr.hotio.dev/hotio/prowlarr:nightly
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - ./data/prowlarr:/config

  autoscan:
    container_name: autoscan
    <<: *env
    image: hotio/autoscan
    depends_on:
      - plex
      - bazarr
      - sonarr
      - radarr
    ports:
      - "3030:3030"
    volumes:
      - ./data/autoscan:/config
  plex:
    container_name: plex
    <<: *env
    image: lscr.io/linuxserver/plex
    ports:
      - 32400:32400
    volumes:
      - ./data/plex/config:/config

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    <<: *env
    image: golift/notifiarr
    ports:
      - "5454:5454"
    volumes:
      - ./data/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      # - /etc/machine-id:/etc/machine-id
